# Generated by Django 4.2.7 on 2026-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtopic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='research_topics/'),
        ),
    ]
