# Generated by Django 4.2.7 on 2026-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_researchtopic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineesubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineesubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
